version = 1

test_patterns = ["tests/**"]
exclude_patterns = ["legacy/**"]

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = false

[[transformers]]
name = "isort"
enabled = false
