project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /i18n/robotoff.pot
    translation: /i18n/%two_letters_code%/LC_MESSAGES/robotoff.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-CN: zh_CN
        zh-HK: zh_HK
        en-GB: en_GB
        en-AU: en_AU
        en-US: en_US
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
