import logging

import requests
from openfoodfacts.ocr import (
    OCRParsingException,
    OCRResult,
    OCRResultGenerationException,
)

from robotoff.utils import http_session

logger = logging.getLogger(__name__)


def get_ocr_result_from_url(
    ocr_url: str,
    session: requests.Session | None = None,
    *,
    error_raise: bool = False,
    warning_missing: bool = True,
) -> OCRResult | None:
    """Fetch an OCR JSON URL and return an OCRResult.

    In production, OCR JSONs are usually generated by Product Opener. In rare
    cases, the OCR payload may contain an error field (e.g. temporary quota
    exhaustion). Depending on the version of `openfoodfacts`, this may bubble
    up as an `OCRParsingException` even when `error_raise=False`.

    This helper ensures Robotoff is resilient to those payloads and returns
    `None` when errors are non-fatal.
    """
    session = http_session if session is None else session
    try:
        return OCRResult.from_url(
            ocr_url,
            session,
            error_raise=error_raise,
            warning_missing=warning_missing,
        )
    except (OCRParsingException, OCRResultGenerationException) as exc:
        if error_raise:
            raise
        logger.warning("Error while fetching OCR JSON from %s", ocr_url, exc_info=exc)
        return None
