services:
  api:
    command:
      - gunicorn
      - --config /opt/robotoff/gunicorn.py
      - --statsd-host=statsd:9125
      - --statsd-prefix=robotoff
      - --log-file=-
      - robotoff.app.api:api
    depends_on:
      - statsd
  statsd:
    restart: $RESTART_POLICY
    image: prom/statsd-exporter:v0.22.2
    volumes:
      - ./statsd.conf:/statsd/statsd.conf
    command:
      - "--statsd.mapping-config=/statsd/statsd.conf"
    ports:
      - ${STATSD_EXPOSE:-9102}:9102
  postgres_exporter:
    restart: $RESTART_POLICY
    image: prometheuscommunity/postgres-exporter:v0.11.1
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgres
    ports:
      - ${POSTGRES_EXPORTER_EXPOSE:-9187}:9187
