import json
from robotoff.types import NutrientData


class TestNutrientData:

    def test_from_webcomponent_json(self):
        # real data generated by webcomponent
        nutrient_data = json.loads("""{
            "nutrients": {
                "energy-kj_100g": {
                    "value": "-",
                    "unit": null
                },
                "energy-kcal_100g": {
                    "value": "190",
                    "unit": "kcal"
                },
                "energy_100g": {
                    "value": "795",
                    "unit": "kcal"
                },
                "fat_100g": {
                    "value": "1.4",
                    "unit": "g"
                },
                "saturated-fat_100g": {
                    "value": "0.4",
                    "unit": "g"
                },
                "carbohydrates_100g": {
                    "value": "35",
                    "unit": "g"
                },
                "sugars_100g": {
                    "value": "1.1",
                    "unit": "g"
                },
                "fiber_100g": {
                    "value": "2.1",
                    "unit": "g"
                },
                "proteins_100g": {
                    "value": "traces",
                    "unit": "g"
                },
                "salt_100g": {
                    "value": "0.03",
                    "unit": "g"
                },
                "sodium_100g": {
                    "value": "0.012",
                    "unit": "g"
                }
            },
            "nutrition_data_per": "100g",
            "serving_size": "1/4 pack"
        }""")
        NutrientData.model_validate(nutrient_data)
