import json

import pytest

from robotoff.types import (
    IngredientAnnotateBody,
    NutrientData,
    NutritionV3,
    NutritionV3InputSet,
)
from tests.unit.data.nutrition import NUTRITION_2


class TestNutrientData:

    def test_from_webcomponent_json(self):
        # real data generated by webcomponent
        nutrient_data = json.loads(
            """{
            "nutrients": {
                "energy-kj_100g": {
                    "value": "-",
                    "unit": null
                },
                "energy-kcal_100g": {
                    "value": "190",
                    "unit": "kcal"
                },
                "energy_100g": {
                    "value": "795",
                    "unit": "kcal"
                },
                "fat_100g": {
                    "value": "1.4",
                    "unit": "g"
                },
                "saturated-fat_100g": {
                    "value": "0.4",
                    "unit": "g"
                },
                "carbohydrates_100g": {
                    "value": "35",
                    "unit": "g"
                },
                "sugars_100g": {
                    "value": "1.1",
                    "unit": "g"
                },
                "fiber_100g": {
                    "value": "2.1",
                    "unit": "g"
                },
                "proteins_100g": {
                    "value": "traces",
                    "unit": "g"
                },
                "salt_100g": {
                    "value": "0.03",
                    "unit": "g"
                },
                "sodium_100g": {
                    "value": "0.012",
                    "unit": "g"
                }
            },
            "nutrition_data_per": "100g",
            "serving_size": "1/4 pack"
        }"""
        )
        NutrientData.model_validate(nutrient_data)


class TestIngredientAnnotateBody:
    def test_ingredient_detection_annotate_body_valid(self):
        body = IngredientAnnotateBody(
            annotation="ingredient",
            rotation=180,
            bounding_box=[0.1, 0.2, 0.5, 0.6],
        )
        assert body.annotation == "ingredient"
        assert body.rotation == 180
        assert body.bounding_box == [0.1, 0.2, 0.5, 0.6]

    def test_ingredient_detection_annotate_body_invalid_length(self):
        with pytest.raises(ValueError):
            IngredientAnnotateBody(
                annotation="ingredient",
                bounding_box=[0.1, 0.2, 0.5],
            )

    def test_ingredient_detection_annotate_body_invalid_coords(self):
        with pytest.raises(ValueError):
            IngredientAnnotateBody(
                annotation="ingredient",
                bounding_box=[0.1, 0.2, 1.5, 0.6],
            )

    def test_ingredient_detection_annotate_body_invalid_order(self):
        with pytest.raises(ValueError):
            IngredientAnnotateBody(
                annotation="ingredient",
                bounding_box=[0.5, 0.2, 0.1, 0.6],
            )


class TestNutritionV3:
    def test_filter_input_sets(self):
        nutrition_obj = NutritionV3.model_validate(NUTRITION_2)
        results = nutrition_obj.filter_input_sets(source="packaging")
        assert len(results) == 1
        assert isinstance(results[0], NutritionV3InputSet)
        assert (
            len(nutrition_obj.filter_input_sets(source="packaging", per="100ml")) == 0
        )

    def test_get_input_nutrient(self):
        nutrition_obj = NutritionV3.model_validate(NUTRITION_2)
        result = nutrition_obj.get_input_nutrient(
            nutrient="sodium",
            per="100g",
            preparation="as_sold",
            per_quantity=100,
            source="packaging",
            per_unit="g",
        )
        assert result is not None
        assert result.value == 2
        assert result.value_string == "2.0"
        assert result.unit == "g"
        assert result.modifier == "<="

        # We expect no result here
        result = nutrition_obj.get_input_nutrient(
            nutrient="sodium",
            # per was modified here
            per="serving",
            preparation="as_sold",
            per_quantity=100,
            source="packaging",
            per_unit="g",
        )
        assert result is None

        result = nutrition_obj.get_input_nutrient(
            nutrient="sugars",
            source="usda",
        )
        assert result is not None
        assert result.value == 5.2
        assert result.value_string == "5.2"
        assert result.unit == "g"
        assert result.modifier is None
