name: Publish PyPI package
on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run poetry build
        run:  poetry build
      - name: Run poetry publish
        run: poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
