name: Publish Docker image
on:
  push:
    tags:
      - v20[0-9][0-9]-[01][0-9]-[0-3][0-9]**

jobs:
  push_to_registry:
    name: Push robotoff Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openfoodfacts/robotoff
          tag_with_ref: true
          add_git_labels: true
